# Generated by Django 6.0.4 on 2026-05-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='dep_name',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('person_type', models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('aged', 'Aged'), ('baby', 'Newly baby')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], max_length=20)),
                ('after_attending', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='department.department')),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
