# Generated by Django 6.0.4 on 2026-05-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_image'),
        ('home', '0004_remove_doctors_dep_name_appointment_delete_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctors'),
        ),
    ]
