# Generated by Django 6.0.4 on 2026-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='after_attending',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('after attending', 'After attending')], max_length=20),
        ),
    ]
